full_rebuild: true
name: Muyao Art
description: # Hallo und herzlich willkommen
destination: jekyllbuild
url: #place url
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
gems: [jekyll-paginate]
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'By Muyao'
media_folder: /media
author_default_avatar: /profile-pic.jpg

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-full"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild]
