# Site information
name: Muyao Art
description: # Hallo und herzlich willkommen
url: #place url
baseurl: #place folder name if site is served in subfolder
author_title_prefix: 'By Muyao'

# Site options
permalink: /:title/
relative_permalinks: false
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination

# Content settings
author_default_avatar: /profile-pic.jpg
tag_dir: /tag
category_dir: /category
author_dir: /author
media_folder: /media

# Build settings
full_rebuild: true
encoding: utf-8
destination: jekyllbuild
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-full"
      type: "standard"
      homedisplay: "featimg"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .git
  - .gitignore
  - .sass-cache
  - README.md
  - gruntfile.js
  - jekyllbuild
  - node_modules
  - package.json
  - sass
