# Site information
name: Muyao Art
description: # Hallo und herzlich willkommen
url: #place url
baseurl: #place folder name if site is served in subfolder
github_branch_edit_url: https://github.com/muyao/muyao.art/edit/master

# Site options
permalink: /:title/
relative_permalinks: false
paginate: 9
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination

# Content settings
tag_dir: /tag
category_dir: /category
media_folder: /media

# Build settings
full_rebuild: true
encoding: utf-8
destination: jekyllbuild
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .git
  - .gitignore
  - .sass-cache
  - README.md
  - gruntfile.js
  - jekyllbuild
  - node_modules
  - package.json
  - sass
